### ISSUE TITLE
No chart data available

### ISSUE THREAD

**Issue by Taakn** [mikemonteith/react-native-mpchart#3]
Hello,

I am getting a "No chart data available" on all your charts (using your examples). I am using React Native 0.19. Do you know what could be causing the issue?

Thanks so much

**Comment by mikemonteith** [comment]
The library was built on React Native v0.17.0 (I'm not sure if that's causing the issue you're having). The library does need to be updated to the most recent React version, hopefully I can get around to checking it out tonight.

**Comment by mikemonteith** [comment]
Updated to react 0.19.0

**Comment by Taakn** [comment]
Thanks so much but I am getting the following error when installing (I uninstalled and tried reinstalling):
`Invalid version: "1.2"`

Maybe because your release version is 1.1.0?

That's the full log, let me know if that helps:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'https://github.com/mikemonteith/react-native-mpchart' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData https://github.com/mikemonteith/react-native-mpchart
8 silly fetchOtherPackageData https://github.com/mikemonteith/react-native-mpchart
9 silly cache add args [ 'https://github.com/mikemonteith/react-native-mpchart', null ]
10 verbose cache add spec https://github.com/mikemonteith/react-native-mpchart
11 silly cache add parsed spec Result {
11 silly cache add   raw: 'https://github.com/mikemonteith/react-native-mpchart',
11 silly cache add   scope: null,
11 silly cache add   name: null,
11 silly cache add   rawSpec: 'https://github.com/mikemonteith/react-native-mpchart',
11 silly cache add   spec: 'git+https://github.com/mikemonteith/react-native-mpchart.git',
11 silly cache add   type: 'hosted',
11 silly cache add   hosted:
11 silly cache add    { type: 'github',
11 silly cache add      ssh: 'git@github.com:mikemonteith/react-native-mpchart.git',
11 silly cache add      sshUrl: 'git+ssh://git@github.com/mikemonteith/react-native-mpchart.git',
11 silly cache add      httpsUrl: 'git+https://github.com/mikemonteith/react-native-mpchart.git',
11 silly cache add      gitUrl: 'git://github.com/mikemonteith/react-native-mpchart.git',
11 silly cache add      shortcut: 'github:mikemonteith/react-native-mpchart',
11 silly cache add      directUrl: 'https://raw.githubusercontent.com/mikemonteith/react-native-mpchart/master/package.json' } }
12 verbose addRemoteGit caching https://github.com/mikemonteith/react-native-mpchart
13 verbose addRemoteGit git+https://github.com/mikemonteith/react-native-mpchart.git is a repository hosted by github
14 silly tryClone cloning git+https://github.com/mikemonteith/react-native-mpchart.git via git+https://github.com/mikemonteith/react-native-mpchart.git
15 verbose tryClone git-https-github-com-mikemonteith-react-native-mpchart-git-ada61319920afc2eb11d323c61eb3d54 not in flight; caching
16 info git [ 'config', '--get', 'remote.origin.url' ]
17 silly validateExistingRemote git+https://github.com/mikemonteith/react-native-mpchart.git remote.origin.url: https://github.com/mikemonteith/react-native-mpchart.git
18 verbose validateExistingRemote git+https://github.com/mikemonteith/react-native-mpchart.git is updating existing cached remote /Users/USER/.npm/_git-remotes/git-https-github-com-mikemonteith-react-native-mpchart-git-ada61319920afc2eb11d323c61eb3d54
19 info git [ 'fetch', '-a', 'origin' ]
20 verbose updateRemote git fetch -a origin (https://github.com/mikemonteith/react-native-mpchart.git)
21 verbose setPermissions git+https://github.com/mikemonteith/react-native-mpchart.git set permissions on /Users/USER/.npm/_git-remotes/git-https-github-com-mikemonteith-react-native-mpchart-git-ada61319920afc2eb11d323c61eb3d54
22 verbose resolveHead git+https://github.com/mikemonteith/react-native-mpchart.git original treeish: master
23 info git [ 'rev-list', '-n1', 'master' ]
24 silly resolveHead git+https://github.com/mikemonteith/react-native-mpchart.git resolved treeish: cc41fb86c2c3fc76ce465cbc077f41fb4c3718b5
25 verbose resolveHead git+https://github.com/mikemonteith/react-native-mpchart.git resolved Git URL: git+https://github.com/mikemonteith/react-native-mpchart.git#cc41fb86c2c3fc76ce465cbc077f41fb4c3718b5
26 silly resolveHead Git working directory: /var/folders/cz/glrj5hdn7cdgw387k_7kxj000000gn/T/npm-90851-776f78f0/git-cache-a58a19aecc16a97ef33f8e38e56ead78/cc41fb86c2c3fc76ce465cbc077f41fb4c3718b5
27 info git [ 'clone',
27 info git   '/Users/USER/.npm/_git-remotes/git-https-github-com-mikemonteith-react-native-mpchart-git-ada61319920afc2eb11d323c61eb3d54',
27 info git   '/var/folders/cz/glrj5hdn7cdgw387k_7kxj000000gn/T/npm-90851-776f78f0/git-cache-a58a19aecc16a97ef33f8e38e56ead78/cc41fb86c2c3fc76ce465cbc077f41fb4c3718b5' ]
28 verbose cloneResolved git+https://github.com/mikemonteith/react-native-mpchart.git clone Cloning into '/var/folders/cz/glrj5hdn7cdgw387k_7kxj000000gn/T/npm-90851-776f78f0/git-cache-a58a19aecc16a97ef33f8e38e56ead78/cc41fb86c2c3fc76ce465cbc077f41fb4c3718b5'...
28 verbose cloneResolved done.
29 info git [ 'checkout', 'cc41fb86c2c3fc76ce465cbc077f41fb4c3718b5' ]
30 verbose checkoutTreeish git+https://github.com/mikemonteith/react-native-mpchart.git checkout Note: checking out 'cc41fb86c2c3fc76ce465cbc077f41fb4c3718b5'.
30 verbose checkoutTreeish
30 verbose checkoutTreeish You are in 'detached HEAD' state. You can look around, make experimental
30 verbose checkoutTreeish changes and commit them, and you can discard any commits you make in this
30 verbose checkoutTreeish state without impacting any branches by performing another checkout.
30 verbose checkoutTreeish
30 verbose checkoutTreeish If you want to create a new branch to retain commits you create, you may
30 verbose checkoutTreeish do so (now or later) by using -b with the checkout command again. Example:
30 verbose checkoutTreeish
30 verbose checkoutTreeish   git checkout -b <new-branch-name>
30 verbose checkoutTreeish
30 verbose checkoutTreeish HEAD is now at cc41fb8... Update readme to react 0.19.0
31 error addLocal Could not install /var/folders/cz/glrj5hdn7cdgw387k_7kxj000000gn/T/npm-90851-776f78f0/git-cache-a58a19aecc16a97ef33f8e38e56ead78/cc41fb86c2c3fc76ce465cbc077f41fb4c3718b5
32 silly fetchPackageMetaData Error: Invalid version: "1.2"
32 silly fetchPackageMetaData     at Object.module.exports.fixVersionField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:186:13)
32 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:32:38
32 silly fetchPackageMetaData     at Array.forEach (native)
32 silly fetchPackageMetaData     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:31:15)
32 silly fetchPackageMetaData     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:338:5)
32 silly fetchPackageMetaData     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
32 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
32 silly fetchPackageMetaData     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
32 silly fetchPackageMetaData     at tryToString (fs.js:414:3)
32 silly fetchPackageMetaData     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
32 silly fetchPackageMetaData  error for https://github.com/mikemonteith/react-native-mpchart [Error: Invalid version: "1.2"]
33 silly rollbackFailedOptional Starting
34 silly rollbackFailedOptional Finishing
35 silly runTopLevelLifecycles Starting
36 silly runTopLevelLifecycles Finishing
37 silly install printInstalled
38 verbose stack Error: Invalid version: "1.2"
38 verbose stack     at Object.module.exports.fixVersionField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:186:13)
38 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:32:38
38 verbose stack     at Array.forEach (native)
38 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:31:15)
38 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:338:5)
38 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
38 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
38 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
38 verbose stack     at tryToString (fs.js:414:3)
38 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
39 verbose cwd /Users/USER/Project/ReactProject
40 error Darwin 15.2.0
41 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "https://github.com/mikemonteith/react-native-mpchart"
42 error node v5.3.0
43 error npm  v3.3.12
44 error Invalid version: "1.2"
45 error If you need help, you may report this error at:
45 error     <https://github.com/npm/npm/issues>
46 verbose exit [ 1, true ]

```

**Comment by mikemonteith** [comment]
Oops looks like I've missed the .0 from the version number. It should be 1.2.0

**Comment by mikemonteith** [comment]
Fixed

**Comment by Taakn** [comment]
Yes thanks so much it's working now!
